apiVersion: v1
kind: Secret
metadata:
  name: seed-sno-bmh-secret
  namespace: seed-sno
data:
  username: <USERNAME>
  password: <PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: seed-sno
data:
  .dockerconfigjson: <PULL SECRET>
type: Opaque
