apiVersion: v1
kind: Secret
metadata:
  name: sno1-bmh-secret
  namespace: sno1
data:
  username: <USERNAME>
  password: <PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: sno1
data:
  .dockerconfigjson: <PULL SECRET>
type: Opaque
